---
- name: Archive build image
  hosts: all
  connection: local
  tasks:
    - name: Archive image locally
      docker_image:
        name: "ansibleimage:v1.${BUILD_ID}"
        archive_path: "./apache-jenkins.tar"
        source: local

- name: Deploy container
  hosts: all
  tasks:
    - name: Copy image to dev
      copy:
        src: "./apache-jenkins.tar"
        dest: "/root/dev/"
        
    - name: Load image
      docker_image:
        name: "ansibleimage:v1.${BUILD_ID}"
        load_path: "/root/dev/apache-jenkins.tar"
        source: load
        
    - name: Start container
      docker_container:
        name: "ansiblecontainer"
        image: "ansibleimage:latest"
        ports:
          - "8585:8080"
        state: started
        
    - name: Remove dev directory
      file:
        path: "/root/dev/"
        state: absent
        
    - name: Tag and push to Docker Hub
      docker_image:
        name: "ansibleimage"
        repository: "secrepo/ansibleimage"
        tag: "latest"
        push: yes
        source: local
