---
- name: Deploy Application
  hosts: all
  become: true
  tasks:
    - name: Ensure application directory exists
      file:
        path: /opt/myapp
        state: directory
        mode: '0755'

    - name: Copy application files
      copy:
        src: /path/to/your/application
        dest: /opt/myapp
        remote_src: yes

    - name: Ensure application service is running
      systemd:
        name: myapp
        state: restarted
